#!/usr/bin/env bash
# Configure Nginx with custom HTTP header X-Served-By

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Remove any existing X-Served-By headers to avoid duplicates
sudo sed -i '/add_header X-Served-By/d' /etc/nginx/sites-available/default
# Add the header with dynamic hostname
sudo sed -i "/server_name _;/a \ \n\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
