#!/usr/bin/env bash
# Configure Nginx with custom HTTP header X-Served-By

sudo apt-get -y update
sudo apt-get -y install nginx

# Set up a simple index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Add X-Served-By header with hostname
sudo sed -i "/server_name _/a \ \n\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
