#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 to load balance web-01 and web-02

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log local0
    maxconn 4096
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web1 44.202.96.98:80 check
    server web2 44.208.26.113:80 check
EOF'

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo haproxy -f /etc/haproxy/haproxy.cfg -c

sudo service haproxy restart
